modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"
issueTrackerURL="https://github.com/Negodya1/Twilight-Aether/issues"

[[mods]] #mandatory
    modId="${mod_id}" #mandatory
    version="${mod_version}" #mandatory
    displayName="${mod_name}" #mandatory
    displayURL="https://github.com/Negodya1/Twilight-Aether"
    logoFile="logo.png" #optional
    #credits="" #optional
    authors="${mod_authors}" #optional
    description='''${mod_description}'''

[[dependencies.${mod_id}]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="aether"
    mandatory=true
    versionRange="[1.4.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="twilightforest"
    mandatory=true
    versionRange="[4.2.1518,)"
    ordering="NONE"
    side="BOTH"

#[features.${mod_id}]
#openGLVersion="[3.2,)"