package com.negodya1.twilightaether;

import com.aetherteam.aether.Aether;
import com.aetherteam.aether.api.AetherMoaTypes;
import com.aetherteam.aether.client.AetherSoundEvents;
import com.aetherteam.aether.entity.AetherEntityTypes;
import com.aetherteam.aether.item.accessories.cape.AgilityCapeItem;
import com.aetherteam.aether.item.accessories.cape.CapeItem;
import com.aetherteam.aether.item.accessories.cape.InvisibilityCloakItem;
import com.aetherteam.aether.item.accessories.cape.ValkyrieCapeItem;
import com.aetherteam.aether.item.accessories.gloves.GlovesItem;
import com.aetherteam.aether.item.accessories.gloves.GoldGlovesItem;
import com.aetherteam.aether.item.accessories.gloves.LeatherGlovesItem;
import com.aetherteam.aether.item.accessories.gloves.ZaniteGlovesItem;
import com.aetherteam.aether.item.accessories.miscellaneous.GoldenFeatherItem;
import com.aetherteam.aether.item.accessories.miscellaneous.IronBubbleItem;
import com.aetherteam.aether.item.accessories.miscellaneous.RegenerationStoneItem;
import com.aetherteam.aether.item.accessories.miscellaneous.ShieldOfRepulsionItem;
import com.aetherteam.aether.item.accessories.pendant.IcePendantItem;
import com.aetherteam.aether.item.accessories.pendant.PendantItem;
import com.aetherteam.aether.item.accessories.pendant.ZanitePendantItem;
import com.aetherteam.aether.item.accessories.ring.IceRingItem;
import com.aetherteam.aether.item.accessories.ring.RingItem;
import com.aetherteam.aether.item.accessories.ring.ZaniteRingItem;
import com.aetherteam.aether.item.combat.*;
import com.aetherteam.aether.item.combat.loot.*;
import com.aetherteam.aether.item.food.AetherFoods;
import com.aetherteam.aether.item.food.GummySwetItem;
import com.aetherteam.aether.item.food.HealingStoneItem;
import com.aetherteam.aether.item.food.WhiteAppleItem;
import com.aetherteam.aether.item.materials.AmbrosiumShardItem;
import com.aetherteam.aether.item.materials.SkyrootStickItem;
import com.aetherteam.aether.item.materials.SwetBallItem;
import com.aetherteam.aether.item.miscellaneous.*;
import com.aetherteam.aether.item.miscellaneous.bucket.*;
import com.aetherteam.aether.item.tools.gravitite.GravititeAxeItem;
import com.aetherteam.aether.item.tools.gravitite.GravititeHoeItem;
import com.aetherteam.aether.item.tools.gravitite.GravititePickaxeItem;
import com.aetherteam.aether.item.tools.gravitite.GravititeShovelItem;
import com.aetherteam.aether.item.tools.holystone.HolystoneAxeItem;
import com.aetherteam.aether.item.tools.holystone.HolystoneHoeItem;
import com.aetherteam.aether.item.tools.holystone.HolystonePickaxeItem;
import com.aetherteam.aether.item.tools.holystone.HolystoneShovelItem;
import com.aetherteam.aether.item.tools.skyroot.SkyrootAxeItem;
import com.aetherteam.aether.item.tools.skyroot.SkyrootHoeItem;
import com.aetherteam.aether.item.tools.skyroot.SkyrootPickaxeItem;
import com.aetherteam.aether.item.tools.skyroot.SkyrootShovelItem;
import com.aetherteam.aether.item.tools.valkyrie.ValkyrieAxeItem;
import com.aetherteam.aether.item.tools.valkyrie.ValkyrieHoeItem;
import com.aetherteam.aether.item.tools.valkyrie.ValkyriePickaxeItem;
import com.aetherteam.aether.item.tools.valkyrie.ValkyrieShovelItem;
import com.aetherteam.aether.item.tools.zanite.ZaniteAxeItem;
import com.aetherteam.aether.item.tools.zanite.ZaniteHoeItem;
import com.aetherteam.aether.item.tools.zanite.ZanitePickaxeItem;
import com.aetherteam.aether.item.tools.zanite.ZaniteShovelItem;
import com.negodya1.twilightaether.item.accessories.capes.FieryCapeItem;
import com.negodya1.twilightaether.item.accessories.gloves.ArcticGlovesItem;
import com.negodya1.twilightaether.item.accessories.gloves.DescriptionGlovesItem;
import com.negodya1.twilightaether.item.accessories.gloves.PhantomGlovesItem;
import net.minecraft.ChatFormatting;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.Style;
import net.minecraft.network.chat.TextColor;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.material.Fluids;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

import twilightforest.enums.TwilightArmorMaterial;

public class TwilightAetherItems {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, TwilightAether.MODID);

    public static final RegistryObject<Item> ARCTIC_GLOVES = ITEMS.register("arctic_gloves", () -> new ArcticGlovesItem(0.5, new Item.Properties().durability(118)));
    public static final RegistryObject<Item> FIERY_GLOVES = ITEMS.register("fiery_gloves", () -> new DescriptionGlovesItem(TwilightArmorMaterial.ARMOR_FIERY, 1.0, TwilightAether.locate("fiery_gloves"), () -> SoundEvents.ARMOR_EQUIP_IRON, new Item.Properties().durability(1024).fireResistant().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> IRONWOOD_GLOVES = ITEMS.register("ironwood_gloves", () -> new GlovesItem(TwilightArmorMaterial.ARMOR_IRONWOOD, 0.5, TwilightAether.locate("ironwood_gloves"), () -> SoundEvents.ARMOR_EQUIP_IRON, new Item.Properties().durability(512)));
    public static final RegistryObject<Item> KNIGHTMETAL_GLOVES = ITEMS.register("knightmetal_gloves",  () -> new DescriptionGlovesItem(TwilightArmorMaterial.ARMOR_KNIGHTLY, 0.75, TwilightAether.locate("knightmetal_gloves"), () -> SoundEvents.ARMOR_EQUIP_IRON, new Item.Properties().durability(512)));
    public static final RegistryObject<Item> NAGA_GLOVES = ITEMS.register("naga_gloves", () -> new GlovesItem(TwilightArmorMaterial.ARMOR_NAGA, 0.5, TwilightAether.locate("naga_gloves"), () -> SoundEvents.ARMOR_EQUIP_LEATHER, new Item.Properties().durability(131)));
    public static final RegistryObject<Item> PHANTOM_GLOVES = ITEMS.register("phantom_gloves", () -> new PhantomGlovesItem(TwilightArmorMaterial.ARMOR_PHANTOM, 0.75, TwilightAether.locate("phantom_gloves"), () -> SoundEvents.ARMOR_EQUIP_IRON, new Item.Properties().durability(512).rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> STEELEAF_GLOVES = ITEMS.register("steeleaf_gloves", () -> new GlovesItem(TwilightArmorMaterial.ARMOR_STEELEAF, 0.35, TwilightAether.locate("steeleaf_gloves"), () -> SoundEvents.ARMOR_EQUIP_LEATHER, new Item.Properties().durability(131)));
    public static final RegistryObject<Item> YETI_GLOVES = ITEMS.register("yeti_gloves", () -> new DescriptionGlovesItem(TwilightArmorMaterial.ARMOR_YETI, 1.0, TwilightAether.locate("yeti_gloves"), () -> SoundEvents.ARMOR_EQUIP_LEATHER, new Item.Properties().durability(1561)));

    public static final RegistryObject<Item> FIERY_CAPE = ITEMS.register("fiery_cape", () -> new FieryCapeItem(new Item.Properties().stacksTo(1).fireResistant().durability(20).rarity(Rarity.UNCOMMON)));
}